[package]
name = "network_program"
version = "0.0.3"
edition = "2021"

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5.29", features = ["derive"] }
rand = "0.9.0"
lz4 = "1.24.0"
crc32fast = "1.3.2"
bincode = "1.3.3"
csv = "1.2"